export const newFoods = [
  {
    userId: "",
    name: "Banana",
    category: "Fruit",
    grouping: "",
    colour: "Yellow",
    flavour: "Sweet",
    texture: "Soft",
    icon: "🍌",
    notes: "",
  },
  {
    userId: "",
    name: "Apple",
    category: "Fruit",
    grouping: "",
    colour: "Green",
    flavour: "Tart",
    texture: "Crunchy",
    icon: "🍏",
    notes: "",
  },
  {
    userId: "",
    name: "Apple",
    category: "Fruit",
    grouping: "",
    colour: "Red",
    flavour: "Sweet",
    texture: "Crunchy",
    icon: "🍎",
    notes: "",
  },
  {
    userId: "",
    name: "Pear",
    category: "Fruit",
    grouping: "",
    colour: "Green",
    flavour: "Sweet",
    texture: "Grainy",
    icon: "🍐",
    notes: "",
  },
  {
    userId: "",
    name: "Orange",
    category: "Fruit",
    grouping: "",
    colour: "Orange",
    flavour: "Sweet, Acidic",
    texture: "Juicy",
    icon: "🍊",
    notes: "",
  },
  {
    userId: "",
    name: "Strawberry",
    category: "Fruit",
    grouping: "",
    colour: "Red",
    flavour: "Sweet, Tart",
    texture: "Soft",
    icon: "🍓",
    notes: "",
  },
  {
    userId: "",
    name: "Grapes",
    category: "Fruit",
    grouping: "",
    colour: "Purple, Green",
    flavour: "Sweet",
    texture: "Crunchy, Soft",
    icon: "🍇",
    notes: "",
  },
  {
    userId: "",
    name: "Pineapple",
    category: "Fruit",
    grouping: "",
    colour: "Yellow",
    flavour: "Sweet, Acidic",
    texture: "Juicy",
    icon: "🍍",
    notes: "",
  },
  {
    userId: "",
    name: "Blueberries",
    category: "Fruit",
    grouping: "",
    colour: "Blue",
    flavour: "Sweet",
    texture: "Soft",
    icon: "🫐",
    notes: "",
  },
  {
    userId: "",
    name: "Blueberries",
    category: "Fruit",
    grouping: "",
    colour: "Blue",
    flavour: "Sweet",
    texture: "Soft",
    icon: "🫐",
    notes: "",
  },
  {
    userId: "",
    name: "Tomato",
    category: "Fruit",
    grouping: "",
    colour: "Red",
    flavour: "Sweet, Tangy",
    texture: "Grainy, Soft",
    icon: "🍅",
    notes: "",
  },
  {
    userId: "",
    name: "Coconut",
    category: "Fruit",
    grouping: "",
    colour: "White",
    flavour: "Milky, Sweet",
    texture: "Firm, Chewy",
    icon: "🥥",
    notes: "",
  },
  {
    userId: "",
    name: "Avocado",
    category: "Fruit",
    grouping: "",
    colour: "Green",
    flavour: "Nutty",
    texture: "Creamy",
    icon: "🥑",
    notes: "",
  },
  {
    userId: "",
    name: "Potato",
    category: "Vegetable",
    grouping: "",
    colour: "White, Beige",
    flavour: "Mild, Earthy",
    texture: "Soft",
    icon: "🥔",
    notes: "",
  },
  {
    userId: "",
    name: "Carrot",
    category: "Vegetable",
    grouping: "",
    colour: "Orange",
    flavour: "Sweet",
    texture: "Crunchy",
    icon: "🥕",
    notes: "",
  },
  {
    userId: "",
    name: "Sweetcorn",
    category: "Vegetable",
    grouping: "",
    colour: "Yellow",
    flavour: "Sweet",
    texture: "Crunchy",
    icon: "🌽",
    notes: "",
  },
  {
    userId: "",
    name: "Bell Pepper",
    category: "Vegetable",
    grouping: "",
    colour: "Red, Green, Yellow, Orange",
    flavour: "Sweet",
    texture: "Crunchy",
    icon: "🫑",
    notes: "",
  },
  {
    userId: "",
    name: "Cucumber",
    category: "Vegetable",
    grouping: "",
    colour: "Green",
    flavour: "Mild",
    texture: "Crunchy, Juicy",
    icon: "🥒",
    notes: "",
  },
  {
    userId: "",
    name: "Lettuce",
    category: "Vegetable",
    grouping: "",
    colour: "Green",
    flavour: "Mild, Bitter",
    texture: "Soft",
    icon: "🥬",
    notes: "",
  },
  {
    userId: "",
    name: "Broccoli (cooked)",
    category: "Vegetable",
    grouping: "",
    colour: "Green",
    flavour: "Mild, Bitter",
    texture: "Soft",
    icon: "🥦",
    notes: "",
  },
  {
    userId: "",
    name: "Peas (cooked)",
    category: "Vegetable",
    grouping: "",
    colour: "Green",
    flavour: "Sweet",
    texture: "Soft",
    icon: "🫛",
    notes: "",
  },
  {
    userId: "",
    name: "Onion (cooked)",
    category: "Vegetable",
    grouping: "",
    colour: "White",
    flavour: "Sweet",
    texture: "Soft",
    icon: "🧅",
    notes: "",
  },
  {
    userId: "",
    name: "Mushroom (cooked)",
    category: "Vegetable",
    grouping: "",
    colour: "White, Beige, Brown",
    flavour: "Earthy, Mild, Umami",
    texture: "Soft",
    icon: "🍄",
    notes: "",
  },
  {
    userId: "",
    name: "Nuts",
    category: "Fruit",
    grouping: "",
    colour: "Beige, Brown",
    flavour: "Earthy, Nutty",
    texture: "Firm, Oily",
    icon: "🥜",
    notes: "",
  },
  {
    userId: "",
    name: "Cheese (cheddar)",
    category: "Dairy",
    grouping: "",
    colour: "Beige, Yellow, Orange",
    flavour: "Milky, Salty, Umami",
    texture: "Firm",
    icon: "🧀",
    notes: "",
  },
  {
    userId: "",
    name: "Beef (stewed)",
    category: "Protein",
    grouping: "",
    colour: "Brown",
    flavour: "Meaty, Umami",
    texture: "Soft, Chewy",
    icon: "🥩",
    notes: "",
  },
  {
    userId: "",
    name: "Chicken (roast)",
    category: "Protein",
    grouping: "",
    colour: "White, Beige",
    flavour: "Mild, Umami",
    texture: "Soft",
    icon: "🍗",
    notes: "",
  },
  {
    userId: "",
    name: "Egg (boiled)",
    category: "Protein",
    grouping: "",
    colour: "White, Yellow",
    flavour: "Rich, Umami",
    texture: "Soft, Rubbery",
    icon: "🍗",
    notes: "",
  },
  {
    userId: "",
    name: "Rice",
    category: "Carbohydrate",
    grouping: "",
    colour: "White",
    flavour: "Bland",
    texture: "Soft, Starchy",
    icon: "🍚",
    notes: "",
  },
  {
    userId: "",
    name: "Spaghetti",
    category: "Carbohydrate",
    grouping: "",
    colour: "Beige",
    flavour: "Bland",
    texture: "Soft, Starchy",
    icon: "🍝",
    notes: "",
  },
  {
    userId: "",
    name: "Chips",
    category: "Carbohydrate",
    grouping: "",
    colour: "Beige",
    flavour: "Salty",
    texture: "Soft, Crunchy",
    icon: "🍟",
    notes: "",
  },
];
