[
  {
    id: 1458,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Coconut",
    detail: "",
    grouping: "Fruit",
    category: "None",
    colour: "White",
    flavour: "Milky, Sweet",
    texture: "Firm, Chewy",
    icon: "🥥",
    notes: "",
    bites: [],
  },
  {
    id: 1490,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Beef",
    detail: "Mince",
    grouping: "Protein",
    category: "Yes",
    colour: "Brown",
    flavour: "Meaty, Umami",
    texture: "Chewy",
    icon: "🐄",
    notes: "",
    bites: [
      {
        id: 381,
        userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
        date: "2023-04-25",
        rating: 4,
        notes: "",
      },
    ],
  },
  {
    id: 1428,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Avocado",
    detail: null,
    grouping: "Fruit",
    category: "",
    colour: "Green",
    flavour: "Nutty",
    texture: "Creamy",
    icon: "🥑",
    notes: "",
    bites: [],
  },
  {
    id: 1429,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Potato",
    detail: null,
    grouping: "Vegetable",
    category: "",
    colour: "White, Beige",
    flavour: "Mild, Earthy",
    texture: "Soft",
    icon: "🥔",
    notes: "",
    bites: [],
  },
  {
    id: 1430,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Carrot",
    detail: null,
    grouping: "Vegetable",
    category: "",
    colour: "Orange",
    flavour: "Sweet",
    texture: "Crunchy",
    icon: "🥕",
    notes: "",
    bites: [
      {
        id: 384,
        userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
        date: "2023-04-26",
        rating: 2,
        notes: "",
      },
    ],
  },
  {
    id: 1432,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Bell Pepper",
    detail: null,
    grouping: "Vegetable",
    category: "",
    colour: "Red, Green, Yellow, Orange",
    flavour: "Sweet",
    texture: "Crunchy",
    icon: "🫑",
    notes: "",
    bites: [],
  },
  {
    id: 1433,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Cucumber",
    detail: null,
    grouping: "Vegetable",
    category: "",
    colour: "Green",
    flavour: "Mild",
    texture: "Crunchy, Juicy",
    icon: "🥒",
    notes: "",
    bites: [],
  },
  {
    id: 1434,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Lettuce",
    detail: null,
    grouping: "Vegetable",
    category: "",
    colour: "Green",
    flavour: "Mild, Bitter",
    texture: "Soft",
    icon: "🥬",
    notes: "",
    bites: [],
  },
  {
    id: 1439,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Nuts",
    detail: null,
    grouping: "Fruit",
    category: "",
    colour: "Beige, Brown",
    flavour: "Earthy, Nutty",
    texture: "Firm, Oily",
    icon: "🥜",
    notes: "",
    bites: [],
  },
  {
    id: 1447,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Bread",
    detail: null,
    grouping: "Carbohydrate",
    category: "No",
    colour: "Beige",
    flavour: "Yeasty, Bland",
    texture: "Dry, Soft",
    icon: "🍞",
    notes: "",
    bites: [],
  },
  {
    id: 1417,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Banana",
    detail: null,
    grouping: "Fruit",
    category: "Yes",
    colour: "Yellow",
    flavour: "Sweet",
    texture: "Soft",
    icon: "🍌",
    notes: "",
    bites: [],
  },
  {
    id: 1454,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Green Beans",
    detail: "Tinned",
    grouping: "Vegetable",
    category: "Yes",
    colour: "Green",
    flavour: "Mild, Earthy",
    texture: "Soft",
    icon: "🟩",
    notes: "",
    bites: [
      {
        id: 375,
        userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
        date: "2023-04-24",
        rating: 5,
        notes: "With bbq sauce",
      },
    ],
  },
  {
    id: 1431,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Sweetcorn",
    detail: null,
    grouping: "Vegetable",
    category: "",
    colour: "Yellow",
    flavour: "Sweet",
    texture: "Crunchy",
    icon: "🌽",
    notes: "",
    bites: [
      {
        id: 312,
        userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
        date: "2023-04-23",
        rating: 5,
        notes: "With gravy",
      },
      {
        id: 376,
        userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
        date: "2023-04-25",
        rating: 4,
        notes: "With gravy",
      },
    ],
  },
  {
    id: 1443,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Egg",
    detail: "Boiled",
    grouping: "Protein",
    category: "Untested",
    colour: "White, Yellow",
    flavour: "Rich, Umami",
    texture: "Soft, Rubbery",
    icon: "🥚",
    notes: "",
    bites: [],
  },
  {
    id: 1444,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Rice",
    detail: null,
    grouping: "Carbohydrate",
    category: "Yes",
    colour: "White",
    flavour: "Bland",
    texture: "Soft, Starchy",
    icon: "🍚",
    notes: "",
    bites: [
      {
        id: 385,
        userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
        date: "2023-04-26",
        rating: 4,
        notes: "",
      },
    ],
  },
  {
    id: 1437,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Onion",
    detail: "Cooked",
    grouping: "Vegetable",
    category: "None",
    colour: "White",
    flavour: "Sweet",
    texture: "Soft",
    icon: "🧅",
    notes: "",
    bites: [],
  },
  {
    id: 1445,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Spaghetti",
    detail: null,
    grouping: "Carbohydrate",
    category: "Yes",
    colour: "Beige",
    flavour: "Bland",
    texture: "Soft, Starchy",
    icon: "🍝",
    notes: "",
    bites: [],
  },
  {
    id: 1440,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Cheese",
    detail: "Cheddar",
    grouping: "Dairy",
    category: "None",
    colour: "Beige, Yellow, Orange",
    flavour: "Milky, Salty, Umami",
    texture: "Firm",
    icon: "🧀",
    notes: "",
    bites: [],
  },
  {
    id: 1438,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Mushroom",
    detail: "Cooked",
    grouping: "Vegetable",
    category: "None",
    colour: "White, Beige, Brown",
    flavour: "Earthy, Mild, Umami",
    texture: "Soft",
    icon: "🍄",
    notes: "",
    bites: [],
  },
  {
    id: 1446,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Chips",
    detail: null,
    grouping: "Carbohydrate",
    category: "Maybe",
    colour: "Beige",
    flavour: "Salty",
    texture: "Soft, Crunchy",
    icon: "🍟",
    notes: "",
    bites: [],
  },
  {
    id: 1418,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Apple",
    detail: null,
    grouping: "Fruit",
    category: "Rarely",
    colour: "Green",
    flavour: "Tart",
    texture: "Crunchy",
    icon: "🍏",
    notes: "",
    bites: [],
  },
  {
    id: 1419,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Apple",
    detail: null,
    grouping: "Fruit",
    category: "Rarely",
    colour: "Red",
    flavour: "Sweet",
    texture: "Crunchy",
    icon: "🍎",
    notes: "",
    bites: [],
  },
  {
    id: 1420,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Pear",
    detail: null,
    grouping: "Fruit",
    category: "Rarely",
    colour: "Green",
    flavour: "Sweet",
    texture: "Grainy",
    icon: "🍐",
    notes: "",
    bites: [],
  },
  {
    id: 1421,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Orange",
    detail: null,
    grouping: "Fruit",
    category: "Yes",
    colour: "Orange",
    flavour: "Sweet, Acidic",
    texture: "Juicy",
    icon: "🍊",
    notes: "",
    bites: [
      {
        id: 374,
        userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
        date: "2023-04-24",
        rating: 3,
        notes: "",
      },
    ],
  },
  {
    id: 1422,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Strawberry",
    detail: null,
    grouping: "Fruit",
    category: "Maybe",
    colour: "Red",
    flavour: "Sweet, Tart",
    texture: "Soft",
    icon: "🍓",
    notes: "",
    bites: [],
  },
  {
    id: 1423,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Grapes",
    detail: null,
    grouping: "Fruit",
    category: "Yes",
    colour: "Purple, Green",
    flavour: "Sweet",
    texture: "Crunchy, Soft",
    icon: "🍇",
    notes: "",
    bites: [],
  },
  {
    id: 1441,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Beef ",
    detail: "Stewed",
    grouping: "Protein",
    category: "Yes",
    colour: "Brown",
    flavour: "Meaty, Umami",
    texture: "Soft, Chewy",
    icon: "🥩",
    notes: "",
    bites: [],
  },
  {
    id: 1435,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Broccoli",
    detail: null,
    grouping: "Vegetable",
    category: "None",
    colour: "Green",
    flavour: "Mild, Bitter",
    texture: "Soft",
    icon: "🥦",
    notes: "",
    bites: [],
  },
  {
    id: 1424,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Pineapple",
    detail: null,
    grouping: "Fruit",
    category: "Yes",
    colour: "Yellow",
    flavour: "Sweet, Acidic",
    texture: "Juicy",
    icon: "🍍",
    notes: "",
    bites: [
      {
        id: 311,
        userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
        date: "2023-04-23",
        rating: 2,
        notes: "",
      },
    ],
  },
  {
    id: 1425,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Blueberries",
    detail: null,
    grouping: "Fruit",
    category: "Yes",
    colour: "Blue",
    flavour: "Sweet",
    texture: "Soft",
    icon: "🫐",
    notes: "",
    bites: [],
  },
  {
    id: 1426,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Tomato",
    detail: null,
    grouping: "Fruit",
    category: "No",
    colour: "Red",
    flavour: "Sweet, Tangy",
    texture: "Grainy, Soft",
    icon: "🍅",
    notes: "",
    bites: [],
  },
  {
    id: 1455,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Sausage",
    detail: null,
    grouping: "Protein",
    category: "Yes",
    colour: "Brown",
    flavour: "Meaty, Salty",
    texture: "Soft, Chewy",
    icon: "🌭",
    notes: "",
    bites: [
      {
        id: 382,
        userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
        date: "2023-04-26",
        rating: 5,
        notes: "Paella",
      },
    ],
  },
  {
    id: 1436,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Peas",
    detail: null,
    grouping: "Vegetable",
    category: "None",
    colour: "Green",
    flavour: "Sweet",
    texture: "Soft",
    icon: "🫛",
    notes: "",
    bites: [
      {
        id: 383,
        userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
        date: "2023-04-26",
        rating: 4,
        notes: "",
      },
    ],
  },
  {
    id: 1442,
    userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
    name: "Chicken",
    detail: "Roast",
    grouping: "Protein",
    category: "Yes",
    colour: "White, Beige",
    flavour: "Mild, Umami",
    texture: "Soft",
    icon: "🍗",
    notes: "",
    bites: [
      {
        id: 313,
        userId: "IgxWA7lmVWgF595oZzTiEMICXtI2",
        date: "2023-04-23",
        rating: 5,
        notes: "With gravy",
      },
    ],
  },
];
